trigger:
  - main

pool:
  name: self-hosted-agent-TM-ZEN4

steps:
  - task: UseDotNet@2
    inputs:
      version: "8.x"

  - script: |
      dotnet restore
      dotnet build --configuration Release
      dotnet pack -c Release -o $(Build.ArtifactStagingDirectory)
    displayName: "Build and Pack NuGet Package"

  - task: NuGetAuthenticate@1

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)
      artifactName: nuget
      publishLocation: pipeline
